# .github/workflows/build.yml
name: Java 14 + Maven 3.6.3 Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 14
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'  # or 'zulu', 'adopt'
          java-version: '14'

      - name: Install Maven 3.6.3
        run: |
          MAVEN_VERSION=3.6.3
          wget https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
          tar -xvzf apache-maven-$MAVEN_VERSION-bin.tar.gz
          sudo mv apache-maven-$MAVEN_VERSION /opt/maven
          echo "MAVEN_HOME=/opt/maven" >> $GITHUB_ENV
          echo "/opt/maven/bin" >> $GITHUB_PATH

      - name: Verify versions
        run: |
          java -version
          mvn -version

      - name: Build with Maven
        run: mvn clean package -DskipTests
