name: Java LTS + Latest Maven Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java LTS (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Recommended for LTS
          java-version: '17'      # or '21' for the newer LTS

      - name: Set up latest Maven
        uses: s4u/setup-maven-action@v1
        with:
          maven-version: 'latest'

      - name: Check versions
        run: |
          java -version
          mvn -version

      - name: Build with Maven
        run: mvn clean install -DskipTests
