name: Print Java and Gradle Version

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [main]

jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java LTS (Temurin 21)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Print Java version
        run: java -version

      - name: Print Gradle version
        run: ./gradlew --version
